### ISSUE TITLE
Goal 1 - Create series of functions w/ wrangling and viz

### ISSUE THREAD

**Issue by vmulholl** [johannesharmse/watsonNLU#2]
## Project Goal 1: Functions w/ Wrangling and Viz

* [ ] create series of functions that include wrangling and visualisations
* [ ] make sure it is output in a useful format

**Comment by johannesharmse** [comment]
## Functionalities to address

### VIsualization

* [ ] text concept and concept score visualization
* [ ]  text keyword relevance visualization
* [ ] text keyword sentiment visualization
* [ ] text keyword emotion visualization

### Data Wrangling

* [ ] determine features of API returned content (first level of list)
* [ ] determine feature attributes of API returned content (second level of list)
* [ ] dynamically convert output list structure to viewable data format (possibly a data frame per feature)

### Additions to API wrapper function

* [ ] additional error handling
* [ ] handling of empty list returned (in the case of limited text to analyse)
* [ ] proper authorization handling (check if auth is being cached)

### Atonimizing of functions

* [ ] Authorization
* [ ] Feature object (object with valid selected features and feature attributes)
* [ ] API wrapper
* [ ] Visualization functions
* [ ] Data structure conversion (eg. list to data frames)
